name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  logger: ^2.1.0
  google_fonts: ^6.1.0
  json_annotation: ^4.9.0
  auto_route: ^7.9.2
  flutter_dotenv: ^5.1.0
  youtube_player_flutter: ^8.1.2
  bloc_concurrency: ^0.2.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^7.3.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
